server:
  port: 8082

custom:
  kafka:
    topic_id: chat
    group_id: group_chat
    server: localhost:9092

spring:
  profiles:
    include: common
  data:
    mongodb:
      uri: mongodb://john:1111@localhost:27018/room?authSource=admin

redis:
  host: localhost
  port: 6379
  password: 1111
  database: 0

