server:
  port: 8081

spring:
  application:
    name: member-service
  profiles:
    include: auth,common
  config:
    import: optional:configserver:${configServer.host:http://localhost:8888}
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/msa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka




management:
  endpoints:
    web:
      exposure:
        include: info,metrics, busrefresh