spring:
  application:
    name: gateway-service
  profiles:
    include: common

  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/login, /member-service/register
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/logout
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
            - AuthorizationFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
            - AuthorizationFilter
