server:
  port: 8000
spring:
  application:
    name: gateway-service
  profiles:
    include: common
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: login-and-register
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/login, /member-service/register
            - Method=POST
          filters:
            - RewritePath=/member-service/(?<segment>.*),/$\{segment}
        - id: logout
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/logout
            - Method=POST
          filters:
            - RewritePath=/member-service/(?<segment>.*),/$\{segment}
            - AuthorizationFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=POST
          filters:
            - RewritePath=/member-service/(?<segment>.*),/$\{segment}
            - AuthorizationFilter

        - id: websocket-service
          uri: ws://CHAT-SERVICE
          predicates:
            - Path=/ws/**

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**, /room/**
            - Method=POST,GET
          filters:
            - AuthorizationFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/actuator/**
          filters:
            - RewritePath=/notification-service/(?<segment>.*),/$\{segment}

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service/(?<segment>.*),/$\{segment}
            - AuthorizationFilter
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, busrefresh