server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GreenTea9227/config
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: info,health, busrefresh
