name: all-service build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: gradle permisson
      run: |
        chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
