name: config-service

on:
  push:
    branches: ['develop/**']
    paths:
      - config-service/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: gradle permisson
      run: |
        chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew :config-service:build
    
